apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: opendatahub
  namespace: production
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-common
      name: odh-common
    - kustomizeConfig:
        overlays:
          - storage-class
          - shared-pvc
        parameters:
          - name: s3_endpoint_url
            value: 'http://s3.openshift-storage'
          - name: storage_class
            value: ocs-storagecluster-ceph-rbd
          - name: jupyterhub_admins
            value: opentlc-mgr
          - name: singleuser_pvc_size
            value: 2Gi
        repoRef:
          name: manifests
          path: jupyterhub/jupyterhub
      name: jupyterhub
    - kustomizeConfig:
        overlays:
          - additional
          - hmf
        repoRef:
          name: manifests
          path: jupyterhub/notebook-images
      name: notebook-images
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odhargo/cluster
      name: odhargo-cluster
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odhargo/odhargo
      name: odhargo
  repos:
    - name: kf-manifests
      uri: >-
        https://github.com/opendatahub-io/manifests/tarball/v0.7-branch-openshift
    - name: manifests
      uri: 'https://github.com/farbodab/odh-manifests/tarball/hmf'
  version: 0.7.0
